# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: FALSE

r:
  - 3.4
  - 3.5
  - 3.6
  - devel

allow_failures:
  - r: devel
    os: linux
  - r: devel
    os: osx
  
os:
  - linux
  - osx

apt_packages:
  - libudunits2-dev


after_success:
   - Rscript -e 'covr::codecov(token="81b75c97-e8ba-4e24-a9cb-21b37cbab05f")'
